local palette = require("miasma.palette")
local config = require("miasma.config")

---Get plugin highlight groups
---@return table<string, vim.api.keyset.highlight>
local function get()
  local p = palette
  local transparent = config.transparent

  local bg = transparent and p.none or p.bg
  local bg_dark = transparent and p.none or p.dark
  local bg_darker = transparent and p.none or p.darker

  return {
    -- Telescope
    TelescopeBorder = { fg = p.brown, bg = bg_dark },
    TelescopePromptBorder = { fg = p.orange, bg = bg_dark },
    TelescopeResultsBorder = { link = "TelescopeBorder" },
    TelescopePreviewBorder = { link = "TelescopeBorder" },
    TelescopeTitle = { fg = p.green, bg = bg_dark },
    TelescopePromptTitle = { link = "TelescopeTitle" },
    TelescopeResultsTitle = { link = "TelescopeTitle" },
    TelescopePreviewTitle = { link = "TelescopeTitle" },
    TelescopeNormal = { bg = transparent and p.none or nil },
    TelescopePromptNormal = {},
    TelescopeSelection = { link = "Visual" },
    TelescopeSelectionCaret = { fg = p.fg, bg = p.olive },
    TelescopeMatching = { link = "Special" },
    TelescopePromptCounter = { link = "TelescopeBorder" },
    TelescopePromptPrefix = { link = "TelescopeTitle" },
    TelescopePreviewLine = { link = "TelescopeSelection" },
    TelescopeResultsFileIcon = { link = "Special" },
    TelescopeMultiIcon = {},
    TelescopeMultiSelection = {},
    TelescopePreviewBlock = {},
    TelescopePreviewCharDev = {},
    TelescopePreviewDate = {},
    TelescopePreviewDirectory = {},
    TelescopePreviewExecute = {},
    TelescopePreviewGroup = {},
    TelescopePreviewHyphen = {},
    TelescopePreviewLink = {},
    TelescopePreviewMatch = {},
    TelescopePreviewMessage = {},
    TelescopePreviewMessageFillchar = {},
    TelescopePreviewNormal = {},
    TelescopePreviewPipe = {},
    TelescopePreviewRead = {},
    TelescopePreviewSize = {},
    TelescopePreviewSocket = {},
    TelescopePreviewSticky = {},
    TelescopePreviewUser = {},
    TelescopePreviewWrite = {},
    TelescopeResultsClass = {},
    TelescopeResultsComment = {},
    TelescopeResultsConstant = {},
    TelescopeResultsDiffUntracked = {},
    TelescopeResultsField = {},
    TelescopeResultsFunction = {},
    TelescopeResultsIdentifier = {},
    TelescopeResultsLineNr = {},
    TelescopeResultsMethod = {},
    TelescopeResultsNormal = {},
    TelescopeResultsNumber = {},
    TelescopeResultsOperator = {},
    TelescopeResultsSpecialComment = {},
    TelescopeResultsStruct = {},
    TelescopeResultsVariable = {},

    -- GitSigns
    GitSignsAdd = { fg = p.green, bg = bg_dark },
    GitSignsChange = { fg = p.brown, bg = bg_dark },
    GitSignsDelete = { fg = p.orange, bg = bg_dark },
    GitSignsChangedelete = { fg = p.orange, bg = bg_dark },
    GitSignsTopdelete = { fg = p.orange, bg = bg_dark },
    GitSignsUntracked = { fg = p.gray, bg = bg_dark },
    GitSignsAddNr = { fg = p.green },
    GitSignsChangeNr = { fg = p.brown },
    GitSignsDeleteNr = { fg = p.orange },
    GitSignsChangedeleteNr = { fg = p.orange },
    GitSignsTopdeleteNr = { fg = p.orange },
    GitSignsUntrackedNr = { fg = p.gray },
    GitSignsAddCul = { fg = p.green },
    GitSignsChangeCul = { fg = p.brown },
    GitSignsDeleteCul = { fg = p.orange },
    GitSignsChangedeleteCul = { fg = p.orange },
    GitSignsTopdeleteCul = { fg = p.orange },
    GitSignsUntrackedCul = { fg = p.gray },
    GitSignsCurrentLineBlame = { fg = p.gray, italic = true },
    -- Staged variants (dimmed)
    GitSignsStagedAdd = { fg = p.staged_add, bg = bg_dark },
    GitSignsStagedChange = { fg = p.staged_change, bg = bg_dark },
    GitSignsStagedDelete = { fg = p.staged_delete, bg = bg_dark },
    GitSignsStagedChangedelete = { fg = p.staged_delete, bg = bg_dark },
    GitSignsStagedTopdelete = { fg = p.staged_delete, bg = bg_dark },
    GitSignsStagedAddNr = { fg = p.staged_add },
    GitSignsStagedChangeNr = { fg = p.staged_change },
    GitSignsStagedDeleteNr = { fg = p.staged_delete },
    GitSignsStagedChangedeleteNr = { fg = p.staged_delete },
    GitSignsStagedTopdeleteNr = { fg = p.staged_delete },

    -- Lazy.nvim
    LazyNormal = { bg = bg_dark },
    LazyButton = { bg = p.bg },
    LazyButtonActive = { fg = p.bg, bg = p.olive },
    LazyH1 = { fg = p.olive, bg = p.bg },
    LazyH2 = { fg = p.olive, bg = p.bg },
    LazySpecial = { fg = p.tan },
    LazyComment = {},
    LazyCommit = {},
    LazyCommitIssue = {},
    LazyCommitScope = {},
    LazyCommitType = {},
    LazyDimmed = {},
    LazyDir = {},
    LazyLocal = {},
    LazyNoCond = {},
    LazyProgressDone = {},
    LazyProgressTodo = {},
    LazyProp = {},
    LazyReasonCmd = {},
    LazyReasonEvent = {},
    LazyReasonFt = {},
    LazyReasonImport = {},
    LazyReasonKeys = {},
    LazyReasonPlugin = {},
    LazyReasonRuntime = {},
    LazyReasonSource = {},
    LazyReasonStart = {},
    LazyTaskError = {},
    LazyTaskOutput = {},
    LazyUrl = {},
    LazyValue = {},

    -- Mason
    MasonNormal = { bg = bg_dark },
    MasonHeader = { fg = p.fg, bg = p.dark },
    MasonHeading = {},
    MasonHighlight = { fg = p.olive, bg = p.bg },
    MasonHighlightBlock = { link = "LazyButtonActive" },
    MasonHighlightBlockBold = { link = "LazyButtonActive" },
    MasonHighlightBlockBoldSecondary = {},
    MasonHighlightBlockSecondary = {},
    MasonHighlightSecondary = {},
    MasonHeaderSecondary = { link = "LazyButtonActive" },
    MasonMuted = { fg = p.tan, bg = p.dark },
    MasonMutedBlock = { link = "MasonMuted" },
    MasonMutedBlockBold = { link = "MasonHighlight" },
    MasonError = {},
    MasonWarning = {},

    -- Which-key
    WhichKey = { fg = p.fg, bg = bg_dark },
    WhichKeyBorder = { bg = bg_dark },
    WhichKeyDesc = { fg = p.green, bg = bg_dark },
    WhichKeyFloat = { bg = bg_dark },
    WhichKeyGroup = { bg = bg_dark },
    WhichKeySeparator = { fg = p.tan, bg = bg_dark },
    WhichKeyValue = { fg = p.tan },

    -- Indent-blankline
    IblIndent = { fg = p.ibl_indent, nocombine = true },
    IblScope = { fg = p.ibl_scope, nocombine = true },
    IblWhitespace = { fg = p.ibl_indent, nocombine = true },

    -- Scrollbar
    ScrollbarCursor = { fg = p.bg },
    ScrollbarCursorHandle = { fg = p.bg, bg = p.dark, blend = 0 },
    ScrollbarHandle = { bg = p.dark, blend = 0 },
    ScrollbarError = { fg = p.brown },
    ScrollbarErrorHandle = { fg = p.brown, bg = p.dark, blend = 0 },
    ScrollbarWarn = { fg = p.orange },
    ScrollbarWarnHandle = { fg = p.orange, bg = p.dark, blend = 0 },
    ScrollbarHint = { fg = p.green },
    ScrollbarHintHandle = { fg = p.green, bg = p.dark, blend = 0 },
    ScrollbarInfo = { fg = p.green },
    ScrollbarInfoHandle = { fg = p.green, bg = p.dark, blend = 0 },
    ScrollbarMisc = { fg = p.rust },
    ScrollbarMiscHandle = { fg = p.rust, bg = p.dark, blend = 0 },
    ScrollbarSearch = { fg = p.tan },
    ScrollbarSearchHandle = { fg = p.tan, bg = p.dark, blend = 0 },
    ScrollbarGitAdd = { fg = p.green },
    ScrollbarGitAddHandle = { fg = p.green, bg = p.dark, blend = 0 },
    ScrollbarGitChange = { fg = p.brown },
    ScrollbarGitChangeHandle = { fg = p.brown, bg = p.dark, blend = 0 },
    ScrollbarGitDelete = { fg = p.orange },
    ScrollbarGitDeleteHandle = { fg = p.orange, bg = p.dark, blend = 0 },

    -- Bufferline
    BufferLineFill = { bg = bg_darker },
    BufferLineBackground = { fg = p.gray, bg = bg_dark },
    BufferLineBuffer = { fg = p.gray, bg = bg_dark },
    BufferLineBufferVisible = { fg = p.visible, bg = bg },
    BufferLineBufferSelected = { fg = p.fg, bg = bg, bold = true },
    BufferLineTab = { fg = p.gray, bg = bg_dark },
    BufferLineTabSelected = { fg = p.fg, bg = bg, bold = true },
    BufferLineTabClose = { fg = p.orange, bg = bg_dark },
    BufferLineIndicatorSelected = { fg = p.olive, bg = bg },
    BufferLineIndicatorVisible = { fg = p.brown, bg = bg },
    BufferLineSeparator = { fg = p.darker, bg = bg_dark },
    BufferLineSeparatorSelected = { fg = p.darker, bg = bg },
    BufferLineSeparatorVisible = { fg = p.darker, bg = bg },
    BufferLineCloseButton = { fg = p.gray, bg = bg_dark },
    BufferLineCloseButtonSelected = { fg = p.orange, bg = bg },
    BufferLineCloseButtonVisible = { fg = p.visible, bg = bg },
    BufferLineModified = { fg = p.brown, bg = bg_dark },
    BufferLineModifiedSelected = { fg = p.tan, bg = bg },
    BufferLineModifiedVisible = { fg = p.brown, bg = bg },
    BufferLineDuplicate = { fg = p.duplicate, bg = bg_dark, italic = true },
    BufferLineDuplicateSelected = { fg = p.gray, bg = bg, italic = true },
    BufferLineDuplicateVisible = { fg = p.duplicate_visible, bg = bg, italic = true },
    BufferLinePick = { fg = p.orange, bg = bg_dark, bold = true },
    BufferLinePickSelected = { fg = p.orange, bg = bg, bold = true },
    BufferLinePickVisible = { fg = p.orange, bg = bg, bold = true },
    BufferLineDiagnostic = { fg = p.gray, bg = bg_dark },
    BufferLineDiagnosticSelected = { fg = p.gray, bg = bg },
    BufferLineDiagnosticVisible = { fg = p.gray, bg = bg },
    BufferLineError = { fg = p.orange, bg = bg_dark },
    BufferLineErrorSelected = { fg = p.orange, bg = bg },
    BufferLineErrorVisible = { fg = p.orange, bg = bg },
    BufferLineErrorDiagnostic = { fg = p.orange, bg = bg_dark },
    BufferLineErrorDiagnosticSelected = { fg = p.orange, bg = bg },
    BufferLineErrorDiagnosticVisible = { fg = p.orange, bg = bg },
    BufferLineWarning = { fg = p.brown, bg = bg_dark },
    BufferLineWarningSelected = { fg = p.brown, bg = bg },
    BufferLineWarningVisible = { fg = p.brown, bg = bg },
    BufferLineWarningDiagnostic = { fg = p.brown, bg = bg_dark },
    BufferLineWarningDiagnosticSelected = { fg = p.brown, bg = bg },
    BufferLineWarningDiagnosticVisible = { fg = p.brown, bg = bg },
    BufferLineHint = { fg = p.green, bg = bg_dark },
    BufferLineHintSelected = { fg = p.green, bg = bg },
    BufferLineHintVisible = { fg = p.green, bg = bg },
    BufferLineHintDiagnostic = { fg = p.green, bg = bg_dark },
    BufferLineHintDiagnosticSelected = { fg = p.green, bg = bg },
    BufferLineHintDiagnosticVisible = { fg = p.green, bg = bg },
    BufferLineInfo = { fg = p.olive, bg = bg_dark },
    BufferLineInfoSelected = { fg = p.olive, bg = bg },
    BufferLineInfoVisible = { fg = p.olive, bg = bg },
    BufferLineInfoDiagnostic = { fg = p.olive, bg = bg_dark },
    BufferLineInfoDiagnosticSelected = { fg = p.olive, bg = bg },
    BufferLineInfoDiagnosticVisible = { fg = p.olive, bg = bg },
    BufferLineNumbers = { fg = p.gray, bg = bg_dark },
    BufferLineNumbersSelected = { fg = p.fg, bg = bg, bold = true },
    BufferLineNumbersVisible = { fg = p.visible, bg = bg },

    -- FzfLua
    FzfLuaBorder = { link = "Normal" },
    FzfLuaCursor = { link = "Cursor" },
    FzfLuaCursorLine = { link = "CursorLine" },
    FzfLuaCursorLineNr = { link = "CursorLineNr" },
    FzfLuaNormal = { link = "Normal" },
    FzfLuaScrollFloatEmpty = { link = "PmenuSbar" },
    FzfLuaScrollFloatFull = { link = "PmenuThumb" },
    FzfLuaSearch = { link = "IncSearch" },

    -- NERDTree
    NERDTreeExecFile = { link = "String" },
    NERDTreeHelp = { link = "Comment" },

    -- CtrlP
    CtrlPLinePre = { link = "Comment" },
    CtrlPMatch = { link = "String" },

    -- Neo-tree (transparency)
    NeoTreeNormal = { bg = transparent and p.none or nil },
    NeoTreeNormalNC = { bg = transparent and p.none or nil },
    NeoTreeEndOfBuffer = { bg = transparent and p.none or nil },
    NeoTreeSignColumn = { bg = transparent and p.none or nil },
    NeoTreeFloatBorder = { bg = transparent and p.none or nil },
    NeoTreeFloatNormal = { bg = transparent and p.none or nil },
    NeoTreeFloatTitle = { bg = transparent and p.none or nil },
    NeoTreeTitleBar = { bg = transparent and p.none or nil },
    NeoTreeCursorLine = { bg = transparent and p.none or nil },
    NeoTreeDirectoryName = { bg = transparent and p.none or nil },
    NeoTreeDirectoryIcon = { bg = transparent and p.none or nil },
    NeoTreeFileName = { bg = transparent and p.none or nil },
    NeoTreeFileIcon = { bg = transparent and p.none or nil },
    NeoTreeGitAdded = { bg = transparent and p.none or nil },
    NeoTreeGitConflict = { bg = transparent and p.none or nil },
    NeoTreeGitDeleted = { bg = transparent and p.none or nil },
    NeoTreeGitIgnored = { bg = transparent and p.none or nil },
    NeoTreeGitModified = { bg = transparent and p.none or nil },
    NeoTreeGitRenamed = { bg = transparent and p.none or nil },
    NeoTreeGitStaged = { bg = transparent and p.none or nil },
    NeoTreeGitUnstaged = { bg = transparent and p.none or nil },
    NeoTreeGitUntracked = { bg = transparent and p.none or nil },

    -- Blink.cmp
    BlinkCmpMenu = { bg = transparent and p.none or nil },
    BlinkCmpMenuBorder = { bg = transparent and p.none or nil },
    BlinkCmpDoc = { bg = transparent and p.none or nil },
    BlinkCmpDocBorder = { bg = transparent and p.none or nil },
    BlinkCmpSignatureHelp = { bg = transparent and p.none or nil },
    BlinkCmpSignatureHelpBorder = { bg = transparent and p.none or nil },
    BlinkCmpMenuSelection = { fg = p.bg, bg = p.olive },

    -- Noice
    NoiceCmdlinePopup = { bg = transparent and p.none or nil },
    NoiceCmdlinePopupBorder = { fg = p.brown, bg = transparent and p.none or nil },
    NoiceCmdlinePopupTitle = { fg = p.green, bg = transparent and p.none or nil },
  }
end

return { get = get }
